### PR TITLE
Bash ver tests

### PR DESCRIPTION
**Pull request by sdolenc**
running automated tests for various bash versions

| OS ver     | bash ver |
|------------|----------|
| Debian 10  | 5.0      |
| Debian 9.0 | 4.4      |
| Debian 8.0 | 4.3      |
| Debian 7.0 | 4.2      |

this starts to resolve issue https://github.com/Checksum/critic.sh/issues/5

### CODE REVIEW

**Comment by sdolenc** [comment]
The commit description describes why changes were made, but to summarize:
1. Empty arrays are treated as unassigned arrays in earlier bash versions (causing `set -u` to complain). The workaround is a somewhat strange syntax, but it's the best I could find https://stackoverflow.com/questions/7577052/bash-empty-array-expansion-with-set-u
1. quoting numbers within $(( )) math expressions can trip up old versions of bash

**Comment by Checksum** [comment]
Thanks for the great work! I'm interested in seeing if we can get the same checks as GitHub Actions to keep it consistent with the existing tests. Been very busy at work, so this may take a couple of days. If that is going to be a lot of work, I'll just merge your changes in as is (any CI is better than no CI 😃 )

**Comment by Checksum** [comment]
I quickly tested running the same on GitHub Actions:

https://github.com/Checksum/critic.sh/blob/master/.github/workflows/main.yml#L16-L20

**Comment by sdolenc** [comment]
Makes sense. I'll take a peak at adjusting my existing PR to use github actions instead. I'll either update this pr with appropriate commit(s) or add comment(s) describing any hurdles I'm seeing.

The main difference I can think of offhand: it'll be easier to use Alpine containers for Bash 4.2 and below. I discovered earlier Debian versions don't work out-of-the-box with github actions because they have trouble installing the minimum node version github actions requires. I can think of some possible workarounds, but I think using Alpine is the easiest/cleanest solution.

The final results would look something like this

| OS | bash ver | CI |
|------------|----------|-----------|
| Debian 10  | 5.0      | yes       |
| Debian 9.0 | 4.4      | yes       |
| Debian 8.0 | 4.3      | yes       |
| Alpine | 4.2      | yes       |
| Alpine | 4.1      | soon      |
| Alpine | 4.0      | tbd       |
| Alpine | 3.2      | tbd       |
| Alpine | 3.1      | tbd       |

I'll aim to investigate this week

**Comment by sdolenc** [comment]
Switching to github actions was easier than I anticipated 👍

**Comment by Checksum** [comment]
LGTM, thanks for picking this up!

**Pull request merged**
